version: '3.7'
services:
  sql-server-db:
    container_name: code_academy
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pro247!!"
      ACCEPT_EULA: "Y"

 